### ISSUE TITLE
Missing space between "ply" command and path name not detected.

### ISSUE THREAD

**Issue by MariamAndersson** [jonhrafe/MCDC_Simulator_public#3]
When using meshes for simulations, the ply command is used, followed by the path name. When there was a missing space between "ply" and the pathname, the simulations ran, but the mesh was not implemented, producing simulations of only free diffusion.

It would be useful with an error message to prevent this issue and notify the user about the mistake.

**Comment by jonhrafe** [comment]
The simulator now warns a user if the <obstacle tag> was initialized, but they "failed"  to initialize a valid obstacle.
