### ISSUE TITLE
Misleading error message upon failed spin initialisation

### ISSUE THREAD

**Issue by MariamAndersson** [jonhrafe/MCDC_Simulator_public#4]
When automatic initialisation of spins within a substrate with "ini_walker_pos intra" fails, the error message is:

"Cannot initialize extra-cellular walkers win the given substrate".

However, the initialisation actually fails due to the fact that the substrate occupies a very small volume fraction of the specified voxel. It would be helpful if the error message reflected this.

**Comment by jonhrafe** [comment]
The system errors have been updated to indicate either if:

- The maximum number of tries to find a intra- or extra- axonal compartments were reached.

- There's no defined threshold where to initialize the particles (missing voxel or sampling area) 

- There's no obstacle(s) defined.

The number of tires was updated to 100,000 (which should work even if you have 1e-5 intra- or -extra axonal volume fractions)
